name: Generate Pages

on:
  push:
    paths:
      - "src/**"
      - ".github/**"
  pull_request:
    paths:
      - "src/**"
      - ".github/**"

jobs:
  build:
    name: Generate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.1.3
        with:
          php-version: "7.4"
          coverage: pcov
          tools: php-cs-fixer, phpunit

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Build Pages
        run: shell/generatepages.sh

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Rebuilt site." -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
